language: julia
matrix:
  include:
    - os: windows
      arch: x86
      julia: 1.2
    - os: windows
      arch: x64
      julia: 1.3

notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      os: linux
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
