language: julia
julia:
  - 1.0
  - 1.1
  - 1.3
os:
  - linux
  - osx
  - windows
    arch: x64
  - windows
    arch: x86

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      os: linux
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
