# language: julia
# matrix:
#   include:
#   - os: linux
#     julia: 1.2
#   - os: osx
#     julia: 1.3

matrix:
  include:
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
    env: ISOLATED=false
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
    env: ISOLATED=true

notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      os: linux
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
