language: julia
julia:
  - 1.3
  - 1.2
  - 1.1
  - 1.0
os:
  - linux
  - osx
matrix:
  include:
    - os: windows
      arch: x86
      julia: 1.2
    - os: windows
      arch: x64
      julia: 1.3

notifications:
  email: false
